from django.urls import path
from . import views

urlpatterns = [
    path('', views.sale_list, name='sale_list'),
    path('pos/', views.pos_view, name='pos'),
    path('new/', views.new_sale, name='new_sale'),
    path('<int:pk>/', views.sale_detail, name='sale_detail'),
    path('<int:pk>/edit/', views.sale_edit, name='sale_edit'),
    path('<int:pk>/delete/', views.sale_delete, name='sale_delete'),
    path('<int:pk>/invoice/', views.sale_invoice, name='sale_invoice'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/add/', views.customer_add, name='customer_add'),
    path('customers/<int:pk>/', views.customer_detail, name='customer_detail'),
    path('customers/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customers/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('expenses/', views.expense_list, name='expense_list'),
    path('expenses/add/', views.expense_add, name='expense_add'),
    path('expenses/<int:pk>/edit/', views.expense_edit, name='expense_edit'),
    path('expenses/<int:pk>/delete/', views.expense_delete, name='expense_delete'),
    path('reports/', views.reports_view, name='reports'),
    path('cash-drawer/', views.cash_drawer, name='cash_drawer'),
    path('cash-drawer/open/', views.cash_drawer_open, name='cash_drawer_open'),
    path('cash-drawer/close/', views.cash_drawer_close, name='cash_drawer_close'),
    path('cash-drawer/overview/', views.cash_drawer_overview, name='cash_drawer_overview'),
    path('credit/', views.credit_list, name='credit_list'),
    path('credit/<int:pk>/', views.credit_detail, name='credit_detail'),
    path('credit/create/<int:customer_pk>/', views.credit_account_create, name='credit_account_create'),
    path('credit/<int:account_pk>/issue/', views.credit_issue, name='credit_issue'),
    path('credit/<int:account_pk>/payment/', views.credit_payment, name='credit_payment'),
    path('credit/<int:account_pk>/return/', views.credit_return, name='credit_return'),
    path('daily-report/', views.daily_report, name='daily_report'),
    path('daily-report/<str:report_date>/', views.daily_report_detail, name='daily_report_detail'),
    path('api/product-search/', views.product_search_api, name='product_search_api'),
    path('api/process-sale/', views.process_sale_api, name='process_sale_api'),
    path('import/customers/', views.import_customers, name='import_customers'),
    path('<int:pk>/receipt/', views.sale_receipt, name='sale_receipt'),
]
