# Generated by Django 6.0.5 on 2026-05-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('sales', '0003_alter_sale_payment_method_salepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='recorded_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
