# Generated by Django 6.0.5 on 2026-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_onlineorder_recorded_sale_onlineorder_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_fee_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
